frontend/components/navigation/Navbar.tsx

Needed because NextJS does not do type checking in dev builds (See: [issue](https://github.com/vercel/next.js/issues/14997)).
Whitespace hidden:

Ensure Navbar returns JSX element.

---

backend/db/migrate/20221011033227_create_active_storage_tables.active_storage.rb

Auto generated by rails
@ganhongyao You can set up the relations for the photos when updating the models. https://api.rubyonrails.org/v6.1.0/classes/ActiveStorage/Attached/Model.html

Install active storage

---

backend/db/schema.rb

Not sure if this was missed out in the #92 PR, but when running `db:migrate` on master branch I get this. Looks like it should be merged.

Apply migrate

---

backend/app/models/campaign.rb
backend/app/models/coupon.rb
backend/app/models/interest.rb
backend/db/seeds.rb

Add seed data

---

backend/app/controllers/charities_controller.rb
backend/app/helpers/base64_helper.rb
backend/app/views/charities/_charity.json.jbuilder
backend/app/views/charities/index.json.jbuilder
backend/app/views/charities/show.json.jbuilder
backend/config/routes.rb

Closes #99 
Must be merged after #131

Implement CharitiesController

---

frontend/frontendApis/charities.ts
frontend/frontendApis/index.ts
frontend/types/charity.ts

Fixes #132
<details>
<summary>Testing stuff.</summary>
```typescript
import api from '../frontendApis';
import { campaignImageBase64 } from '../utils/examples';
const { charities: charitiesApi, admins: adminsApi } = api;
function wrap<T>(p: Promise<T>): Promise<T> {
return p
.then((x) => {
console.dir(x);
return x;
})
.catch((e) => {
console.error(e);
throw e;
});
}
Promise.resolve().then(async () => {
await wrap(charitiesApi.list());
await adminsApi.loginAdmin({ username: 'x', password: '123456' });
const { payload } = await wrap(
charitiesApi.addCharity({
name: 'Ax',
description: 'xo',
websiteUrl: 'https://www.ax.xo',
logoBase64: campaignImageBase64,
imageBase64: campaignImageBase64,
}),
);
await wrap(charitiesApi.deleteCharity(payload!.id));
await wrap(charitiesApi.list());
const { …
```

Add charities frontend APIs

---

frontend/components/interests/form/InterestForm.tsx
frontend/components/interests/form/InterestFormTextInput.tsx

Disable autocomplete for campaign name.

---

frontend/components/navigation/NavDrawer.tsx

Fix logout

---

backend/app/controllers/interests_controller.rb
backend/app/models/campaign.rb
backend/app/models/interest.rb
backend/config/routes.rb

Update interest controller

---

backend/app/controllers/application_controller.rb
backend/app/controllers/campaigns_controller.rb
backend/app/controllers/charities_controller.rb
backend/app/controllers/interests_controller.rb
backend/app/controllers/secondary_donations_controller.rb
backend/app/models/campaign.rb
backend/app/models/interest.rb
backend/config/initializers/underscore_params.rb

Closes #98
sample POST
```json
{
"name": "siva",
"description": "testing1234",
"promisedAmount": 1000,
"start": "2022-10-10T14:48:00.000Z",
"end": "2022-10-11T14:48:00.000Z",
"primaryDonor": {
"name": "Siva",
"email": "siva@siva.com"
},
"couponDenomination": 10,
"charities": [
{
"charity": {
"id": 3
},
"givingSgUrl": "https://givingsg.com/1"
},
{
"charity": {
"id": 2
},
"givingSgUrl": "https://givingsg.com/2"
}
],
"imageBase64": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAApgAAAKYB3X3/OAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAANCSURBVEiJtZZPbBtFFMZ/M7ubXdtdb1xSFyeilBapySVU8h8OoFaooFSqiihIVIpQBKci6KEg9Q6H9kovIHoCIVQJJCKE1ENFjnAgcaSGC6rEnxBwA04Tx43t2FnvDAfjkNibxgHxnWb2e/u992bee7tCa00YFsffekFY+nUzFtjW0LrvjRXrCDIAaPLlW0nHL0Ss …
```

Campaigns controller part 2

---

frontend/components/campaigns/dashboard/CampaignInfoCard.tsx
frontend/pages/admin/campaigns/index.tsx
frontend/types/campaigns.ts
frontend/utils/campaigns.ts

Fix admin campaign list

---

frontend/styles/globals.scss

Remove overflow-y in globals.scss

---

frontend/frontendApis/interceptor.tsx

Fix no notif on api network error.

---

frontend/pages/campaigns/index.tsx
frontend/styles/pages/campaigns/indexStyles.ts

Closes #204 
Should the message say "No campaigns found"?

Add message when there are no campaign results

---

frontend/components/forms/FormTextInput.tsx
frontend/pages/admin/sign-in.tsx
frontend/pages/admin/sign-up.tsx

Use Formik and disable if !dirty on admin login/signup.

---

frontend/components/campaigns/form/CampaignForm.tsx
frontend/components/campaigns/search/CampaignSearchCheckbox.tsx
frontend/components/campaigns/search/CampaignSearchDatePicker.tsx
frontend/frontendApis/interceptor.tsx
frontend/utils/dates.ts

Covers most of #173 except for Simple Table (#214)

Switch to type-safe unknown instead of any.

---

backend/app/controllers/campaigns_controller.rb

Fix campaign charity not saving edits.

---

backend/app/controllers/campaigns_controller.rb
backend/app/controllers/charities_controller.rb
backend/app/controllers/coupons_controller.rb
backend/app/controllers/interests_controller.rb
backend/app/models/campaign.rb
backend/app/models/campaign_charity.rb
backend/app/models/coupon.rb
backend/app/models/secondary_donation.rb
backend/app/views/coupons/_coupon.json.jbuilder
backend/db/migrate/20221018180806_add_is_redeemed_to_coupon.rb
backend/db/migrate/20221019162926_add_unique_constraint_to_secondary_donation_coupons.rb
backend/db/schema.rb

Fix N+1 queries

---

frontend/components/redeem/VerifyRedemption.tsx
frontend/styles/redeem/VerifyRedemptionStyles.ts

Implement verify redemption

---

frontend/components/generic/SimpleTable.tsx
frontend/styles/components/SimpleTable/simpleTableStyles.ts

Make header sticky and set a maxHeight for table.

---

frontend/components/redeem/CallToActionButton.tsx
frontend/styles/components/redeem/CallToActionButtonStyles.ts
frontend/styles/redeem/thankYou.ts

Fix buttons

---

frontend/components/campaigns/campaignCharities/CampaignCharityDialog.tsx
frontend/styles/components/charities/CampaignCharityDialogStyles.ts

Fix charity dialog

---

backend/app/controllers/coupons_controller.rb
backend/app/controllers/secondary_donations_controller.rb
frontend/components/redeem/ThankYou.tsx
frontend/styles/redeem/thankYou.ts

Fixes #290
- Remove additional thank you.
- Hide lottie overflow.

Fix horizontal scroll on TQ page

---

frontend/components/redeem/DidYouKnow.tsx
frontend/styles/components/redeem/DidYouKnowStyles.ts

Closes #303 
Not sure what design is best but I removed the box first to match our color scheme. Will probably reconsider the style later.

Remove box

---

backend/app/views/campaigns/index.json.jbuilder
frontend/components/campaigns/dashboard/CampaignDonationBreakdownCard.tsx
frontend/components/campaigns/dashboard/CampaignPrimaryDonorCard.tsx
frontend/components/campaigns/list/CampaignListCard.tsx
frontend/pages/index.tsx
frontend/styles/indexStyles.ts
frontend/types/campaigns.ts

Minimal changes (that don't require backend update as well).

Start on fixing up text.

---

frontend/components/redeem/RedirectDialog.tsx

Add text to return by scanning QR code again.

---

frontend/components/campaigns/campaignCharities/CampaignCharityDialog.tsx
frontend/styles/components/charities/CampaignCharityDialogStyles.ts

Fixes #351
At med or smaller:
At larger:

Make changes to visit button and close button.

---

frontend/styles/components/redeem/InstructionDialogStyles.ts

https://user-images.githubusercontent.com/71375383/199082645-8a7fcf97-77d8-4bf4-8fa5-2dc98d04f05c.mov

Fix page moving

---

frontend/components/campaigns/campaignCharities/CampaignCharityCard.tsx
frontend/components/redeem/steps/CharitySelectionStep.tsx
frontend/styles/components/charities/CampaignCharityCardStyles.ts
frontend/styles/components/charts/SmallCompetingGraphStyles.ts

Fixes #350 
On large screen:
On just med:
On small:
handle Click / open:
https://user-images.githubusercontent.com/7360964/199061210-5cd07fd1-f627-41bd-b8e7-7ddeba68ba47.mp4

Add Info button to charity selection card.

---

frontend/styles/components/charities/CampaignCharityDialogStyles.ts

Closes #375 
https://user-images.githubusercontent.com/53614454/199295379-adc8f445-6012-4b37-b3c0-0624dc4ba2f5.mp4

Fix dialog scaling

---

frontend/components/campaigns/campaignCharities/CampaignCharityCard.tsx
frontend/components/charts/SmallCompetingGraph.tsx
frontend/styles/components/charities/CampaignCharityCardStyles.ts
frontend/styles/components/charts/SmallCompetingGraphStyles.ts

Refactor charity card

---

frontend/components/redeem/steps/PersonalContributionStep.tsx
frontend/styles/components/redeem/RedeemStyles.ts

Closes #349 
https://user-images.githubusercontent.com/75519136/199307791-2ac9b3ce-48a2-4c7f-9ebc-edeec7346207.mov

Add emoji based on personal contribution amount

---

frontend/pages/index.tsx

Fix alignment

---

frontend/components/campaigns/dashboard/CampaignCouponsCard.tsx
frontend/components/campaigns/dashboard/CampaignDonationBreakdownCard.tsx
frontend/components/campaigns/dashboard/CampaignInfoCard.tsx
frontend/components/campaigns/dashboard/CampaignLoading.tsx
frontend/pages/admin/campaigns/[campaignId]/index.tsx
frontend/styles/components/campaigns/dashboard/CampaignDashboardStyles.ts

Closes #354
Closes #309 
Also changed 'View unredeemed" button to "Download for distribution". Can suggest a better word choice if you have one.

Update admin page

---

backend/app/views/campaigns/index.json.jbuilder
frontend/components/campaigns/list/CampaignListCard.tsx
frontend/types/campaigns.ts
frontend/utils/dates.ts

Remove contribute button when campaign is not active

---

backend/app/views/coupons/_list.json.jbuilder
backend/app/views/secondary_donations/_secondary_donation.json.jbuilder
frontend/components/campaigns/dashboard/CampaignCouponsCard.tsx
frontend/components/campaigns/dashboard/CampaignNonCouponDonationsCard.tsx
frontend/types/donations.ts
frontend/utils/constants.ts

Redemption and donation timestamps

---

frontend/package.json
frontend/yarn.lock

Reverts Giving-Coupons/giving-coupons#399

Revert "Bump @types/react from 18.0.24 to 18.0.25 in /frontend"

---

backend/app/models/redemption.rb
backend/app/models/secondary_donation.rb
backend/db/seeds.rb

Fix broken seeds

---

frontend/package.json
frontend/yarn.lock

Fix critical security warning

---

frontend/components/campaigns/list/CampaignListCard.tsx

Add date information when campaign is inactive

---

frontend/frontendApis/base.ts
frontend/utils/image.ts

Make a shallow copy of frozen objects instead.

---

frontend/components/campaigns/campaignCharities/CampaignCharityAccordionCard.tsx
frontend/components/campaigns/campaignCharities/CampaignCharityOverview.tsx
frontend/components/campaigns/dashboard/CampaignPublicInfoCard.tsx
frontend/components/campaigns/dashboard/CouponHelpDialog.tsx
frontend/pages/campaigns/[campaignId]/index.tsx
frontend/styles/components/campaigns/dashboard/CampaignDashboardStyles.ts
frontend/utils/constants.ts

Closes #390 
Feel free to suggest changes to phrasing.

Update campaign details page

---

frontend/components/interests/form/InterestForm.tsx
frontend/styles/admin/charities/editStyles.ts
frontend/styles/components/charities/CampaignCharityDialogStyles.ts
frontend/styles/components/charities/CampaignCharityListStyles.ts
frontend/styles/components/charts/SmallCompetingGraphStyles.ts
frontend/styles/components/coupons/couponStyles.tsx
frontend/styles/components/generic/BoldTextStyles.ts
frontend/types/utils.ts

Remove unused exports.

---

backend/app/controllers/campaigns_controller.rb
backend/app/controllers/coupons_controller.rb
backend/app/views/coupons/campaign_unredeemed.json.jbuilder
frontend/components/coupons/CouponFront.tsx
frontend/frontendApis/coupons.ts
frontend/pages/admin/campaigns/[campaignId]/coupons.tsx
frontend/styles/components/coupons/couponStyles.tsx
frontend/types/coupons.ts

Closes https://github.com/Giving-Coupons/giving-coupons/issues/433

Unhardcode donor

---

frontend/components/campaigns/CampaignDescription.tsx
frontend/components/campaigns/campaignCharities/CampaignCharityAccordionCard.tsx
frontend/components/campaigns/campaignCharities/CampaignCharityDialog.tsx
frontend/components/campaigns/dashboard/CampaignInfoCard.tsx
frontend/components/campaigns/dashboard/CampaignPublicInfoCard.tsx
frontend/components/campaigns/list/CampaignListCard.tsx

Fix multi-paragraph descriptions

---

frontend/components/campaigns/dashboard/CampaignCouponsCard.tsx
frontend/components/campaigns/form/CampaignForm.tsx
frontend/components/campaigns/form/CouponRegenerationFormDialog.tsx
frontend/components/forms/FormDatePicker.tsx

Related to #453, but on the regeneration side.

Coupons ought to only expire at the end of the day

---

frontend/components/redeem/steps/PersonalContributionStep.tsx

Fix problem w personal contribution = "0" or "".
